---

- name: Check command to disable IPv6
  command: grep "net.ipv6.conf.all.disable_ipv6 = 1" /etc/sysctl.conf
  changed_when: false
  failed_when: false
  register: line_present

- name: Disable IPv6
  lineinfile: dest=/etc/sysctl.conf
              line="\nnet.ipv6.conf.all.disable_ipv6 = 1"
              state=present
  when: line_present|failed
